service: product-service

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: ap-south-1

plugins:
#  - serverless-iam-role-per-function
  - serverless-offline

functions:
  getProduct:
    handler: functions/getProduct.handler
    events:
      - http:
          path: get/products
          method: get
      - http:
          path: get/product/{id}
          method: get
      - http:
          path: get/my/products
          method: get

#  createProduct:
#    handler: functions/createProduct


custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
    stage: dev
    region: ap-south-1
    lambdaPort: 3002