service: product-service

useDotenv: true
provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    COGNITO_USER_POOL_ID: ${env:UserPoolID}
    COGNITO_USER_POOL_CLIENT_ID: ${env:CognitoClientId}

plugins:
#  - serverless-aws-documentation
  - serverless-dotenv-plugin
#  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  # - serverless-domain-manager
#  - serverless-iam-roles-per-function
#  - serverless-deployment-bucket

functions:
  - ${file(functions/product/index.yml)}
  - ${file(functions/category/index.yml)}
  - ${file(functions/size/index.yml)}
  - ${file(functions/users/index.yml)}
  - ${file(functions/type/index.yml)}
  - ${file(functions/color/index.yml)}
  - ${file(functions/s3/index.yml)}

custom:
  cognitoUserPoolArn: arn:aws:cognito-idp:${self:provider.region}:${env:AccountID}:userpool/${env:UserPoolID}
  serverless-offline:
    host: 0.0.0.0
    port: 3000
    stage: dev
    region: ap-south-1
    lambdaPort: 3002

#  pythonRequirements:
#    dockerizePip: true
#    slim: true  # Only include necessary files
#    strip: true  # Remove unnecessary symbols
#    layer: true  # Use a Lambda layer for dependencies

  prune:
    automatic: true
    number: 1  # Keep only last version

package:
  individually: false
  include:
    - .env
