service: product-service

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: ap-south-1

plugins:
  - serverless-offline
#  - serverless-python-requirements
#  - serverless-iam-roles-per-function

functions:
  - ${file(functions/product/index.yml)}
  - ${file(functions/category/index.yml)}
  - ${file(functions/size/index.yml)}
  - ${file(functions/users/index.yml)}
  - ${file(functions/type/index.yml)}
  - ${file(functions/color/index.yml)}

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
    stage: dev
    region: ap-south-1
    lambdaPort: 3002
