service: product-service

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: ap-south-1
  environment:
    USER_POOL_ID: ap-south-1_odBZSxGsY # Corrected the typo
    APP_CLIENT_ID: 1l58i8qt14oehc4c3c132ieis0
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cognito-idp:SignUp"
            - "cognito-idp:AdminCreateUser"
            - "cognito-idp:AdminInitiateAuth"
            - "cognito-idp:AdminRespondToAuthChallenge"
            - "cognito-idp:ListUsers"
          Resource: "arn:aws:cognito-idp:ap-south-1:058264458029:userpool/ap-south-1_odBZSxGsY"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "*"

plugins:
  - serverless-python-requirements
  - serverless-offline

functions:
  - ${file(functions/product/index.yml)}
  - ${file(functions/category/index.yml)}
  - ${file(functions/size/index.yml)}
  - ${file(functions/users/index.yml)}
  - ${file(functions/type/index.yml)}
  - ${file(functions/color/index.yml)}

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
    stage: dev
    region: ap-south-1
    lambdaPort: 3002

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - arn:aws:cognito-idp:ap-south-1:058264458029:userpool/ap-south-1_odBZSxGsY