service: product-service

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: ap-south-1

plugins:
#  - serverless-aws-documentation
#  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin
  # - serverless-domain-manager
#  - serverless-iam-roles-per-function
#  - serverless-deployment-bucket

functions:
  - ${file(functions/product/index.yml)}
  - ${file(functions/category/index.yml)}
  - ${file(functions/size/index.yml)}
  - ${file(functions/users/index.yml)}
  - ${file(functions/type/index.yml)}
  - ${file(functions/color/index.yml)}

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
    stage: dev
    region: ap-south-1
    lambdaPort: 3002

  pythonRequirements:
    dockerizePip: true
    slim: true  # Only include necessary files
    strip: true  # Remove unnecessary symbols
    layer: true  # Use a Lambda layer for dependencies

  prune:
    automatic: true
    number: 1  # Keep only last version