name: Deploy Serverless Application

on:
  push:
    branches:
      - dev
      - uat
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Serverless Framework
      run: |
        npm install -g serverless

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ap-south-1

    - name: deploy
      run: |
        npx ncc build index.ts
        zip -j deploy.zip ./dist/*
        aws lambda update-function-code --function-name=lambda-gh-action --zip-file=fileb://deploy.zip